# Generated by Django 4.2.2 on 2023-06-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='updated_date',
            new_name='updated_on',
        ),
    ]
