# Generated by Django 4.2.2 on 2023-06-23 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_appointmententry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmententry',
            options={'ordering': ['-date', '-time_from'], 'verbose_name_plural': 'Appointment Entries'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': "Users' Settings"},
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Target')),
                ('order', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Targets',
                'ordering': ['created_on'],
            },
        ),
    ]
