# Generated by Django 4.2.2 on 2023-06-24 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_created_date_usersettings_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmententry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
