# Generated by Django 4.2.2 on 2023-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_appointmententry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
