# Generated by Django 4.2.2 on 2023-06-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_appointmententry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmententry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
