# Generated by Django 4.2.2 on 2023-06-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_alter_appointmententry_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmententry",
            options={
                "ordering": ["date", "time_from"],
                "verbose_name_plural": "Appointment Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="target",
            options={"ordering": ["order"], "verbose_name_plural": "Targets"},
        ),
        migrations.RenameField(
            model_name="winentry",
            old_name="content",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="target",
            name="order",
            field=models.IntegerField(verbose_name="Order"),
        ),
    ]
