# Generated by Django 4.2.2 on 2023-06-30 17:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_noteentry_delete_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gratitudeentry",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Gratitude Entry"),
        ),
        migrations.AlterField(
            model_name="ideasentry",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Ideas Entry"),
        ),
        migrations.AlterField(
            model_name="improvemententry",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Improvement Entry"),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Knowledge Entry"),
        ),
        migrations.AlterField(
            model_name="noteentry",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Notes"),
        ),
    ]
