# Generated by Django 4.2.2 on 2023-06-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_winentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winentry',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Win Entry'),
        ),
        migrations.CreateModel(
            name='IdeasEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Ideas Entry')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ideas Entries',
                'ordering': ['created_on'],
            },
        ),
    ]
