# Generated by Django 4.2.2 on 2023-07-10 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0008_alter_gratitudeentry_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(default="default-slug", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="unique_identifier",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
