# Generated by Django 4.2.2 on 2023-06-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_emotionentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionentry',
            old_name='content',
            new_name='emotion',
        ),
    ]
